create table if not exists public.daily_headlines (
  id bigint generated by default as identity primary key,
  display_date date not null,
  title text not null check (length(trim(title)) > 0),
  publisher text not null,
  article_url text not null check (article_url ~ '^https?://'),
  published_date timestamptz,
  category text not null default 'Healthcare Signal',
  created_at timestamptz not null default now(),
  constraint daily_headlines_display_date_article_url_key unique (display_date, article_url)
);

create index if not exists daily_headlines_display_date_article_url_idx
  on public.daily_headlines (display_date desc, article_url);

alter table public.daily_headlines enable row level security;
revoke all on table public.daily_headlines from anon, authenticated;

comment on table public.daily_headlines is
  'Persistent four-article daily headline sets keyed to America/Chicago calendar dates.';
