create table if not exists public.daily_headline_sets (
  id bigint generated by default as identity primary key,
  display_date date not null,
  article_title text not null check (length(trim(article_title)) > 0),
  article_url text not null check (article_url ~ '^https?://'),
  publisher text not null,
  published_date timestamptz,
  category text not null default 'Healthcare Signal',
  created_at timestamptz not null default now(),
  constraint daily_headline_sets_display_date_url_key unique (display_date, article_url)
);

create index if not exists daily_headline_sets_display_date_idx
  on public.daily_headline_sets (display_date desc);

alter table public.daily_headline_sets enable row level security;
revoke all on table public.daily_headline_sets from anon, authenticated;

comment on table public.daily_headline_sets is
  'One persistent four-article headline edition per America/Chicago calendar day.';
